### ISSUE TITLE
Error after inserting

### ISSUE THREAD

**Issue by mahdiar** [amirnajaffi/shamsi-calendar-plasmoid#1]
Hi
I add it to the panel and it shows an icon. When I click on it shows following error:

```
Error loading QML file: file:///home/mahdiar/.local/share/plasma/plasmoids/org.kde.plasma.shamsi-calendar/contents/ui/main.qml:5:1: Script file:///home/mahdiar/.local/share/plasma/plasmoids/org.kde.plasma.shamsi-calendar/contents/js/main.js unavailable
file:///home/mahdiar/.local/share/plasma/plasmoids/org.kde.plasma.shamsi-calendar/contents/js/main.js:41:32: Unexpected token `?'
file:///home/mahdiar/.local/share/plasma/plasmoids/org.kde.plasma.shamsi-calendar/contents/js/main.js:41:51: Syntax error
```

**Comment by amirnajaffi** [comment]
Hi
Can you give me the software information of your system?
You can find information in the Software part of System Settings -> System Information.

**Comment by mahdiar** [comment]
```
Operating System: Kubuntu 20.10
KDE Plasma Version: 5.19.5
KDE Frameworks Version: 5.74.0
Qt Version: 5.14.2
Kernel Version: 5.8.0-48-generic
OS Type: 64-bit
Processors: 8 × Intel® Core™ i7-4820K CPU @ 3.70GHz
Memory: ۱۵٫۶ GiB of RAM
Graphics Processor: GeForce GTX 770/PCIe/SSE2
```

**Comment by mahdiar** [comment]
I'm not the only person have this issue.
You can check the comments here: [https://store.kde.org/p/1460130/](https://store.kde.org/p/1460130/ )

**Comment by amirnajaffi** [comment]
I can guarantee that this plasmoid works perfectly with the latest version of KDE on Arch Linux(as my system is).
But in your case, I can guess the problem but not what causes the problem. Maybe it's the QT version or the KDE frameworks version!? as you can see my software information :
```
Operating System: Arch Linux
KDE Plasma Version: 5.21.3
KDE Frameworks Version: 5.80.0
Qt Version: 5.15.2
Kernel Version: 5.11.10-arch1-1
OS Type: 64-bit
```
I read those comments but haven't had any clue by 'have an error' or 'have error in syntax'!
Anyway, I have made some changes quickly for Kubuntu compatibility but need to install Kubuntu on a virtual machine for test purposes(I don't think there is another way).
It may take a while so I will inform you.

**Comment by amirnajaffi** [comment]
Fixed in 7772187dffa66b43283991f7e77b9017266ce7fa and cb8be768a5409946b15b9edbb65a20fbb54b7543.

**Comment by mahdiar** [comment]
Thanks.
I can update to the latest version. it shows following error:
`Failed to execute install script `

**Comment by amirnajaffi** [comment]
Try to uninstall, logout, and install it again.

**Comment by mahdiar** [comment]
I uninstalled it and reboot but same error appears.

**Comment by mahdiar** [comment]
I test it in another PC and have the same issue.

**Comment by amirnajaffi** [comment]
Could you try downloading from the KDE store and manual install?
I've tested with fresh Kubuntu 20.10 without a problem.

**Comment by mahdiar** [comment]
I manually deleted its folder and could install it successfully.

**Comment by amirnajaffi** [comment]
Glad to header that. 
Thanks for the info.
