### ISSUE TITLE
V2 testing

### ISSUE THREAD

**Issue by amirnajaffi** [amirnajaffi/shamsi-calendar-plasmoid#11]
@MasterKia @shosseinib @mahdiar @ekm507

Hi
[~~2.0.0-beta.1~~](https://github.com/amirnajaffi/shamsi-calendar-plasmoid/releases/tag/2.0.0-beta.1) [2.0.0-beta.2](https://github.com/amirnajaffi/shamsi-calendar-plasmoid/releases/tag/2.0.0-beta.2) released.
I mentioned you based on your previous activity in this repository.
We are in the testing stage, so I would be grateful if you could install and use the new version.
In case of bugs or ideas(#10) feel free to open issue/PR.

## Installation guide
1. Remove previous version:
```
kpackagetool5 -t Plasma/Applet --remove org.kde.plasma.shamsi-calendar
```
2. Log Out/In
3. Clone/Download repo:
```
git clone https://github.com/amirnajaffi/shamsi-calendar-plasmoid.git
```
4. In root of cloned/downloaded(unzipped) repo:
```
kpackagetool5 -t Plasma/Applet --install package 
```

**Comment by ekm507** [comment]
سلام! بابت تأخیر در پاسخ عذرخواهی می‌کنم.
امتحانش کردم. خیلی خوب شده و پایداره.
بخش تنظیمات هم جالب شده.
نگارش جدید مبارک :))

**Comment by amirnajaffi** [comment]
> سلام! بابت تأخیر در پاسخ عذرخواهی می‌کنم. امتحانش کردم. خیلی خوب شده و پایداره. بخش تنظیمات هم جالب شده. نگارش جدید مبارک :))

سلام و ارادت!
ممنون که تست کردید
دیگه جدیدترشم اومد :)) وقت بشه changelog و readme جدید بنویسم :))
تنطیمات سایز فونت پنل اضافه شده و رفع باگ‌های جزئی و بهبود.

**Comment by amirnajaffi** [comment]
[2.0.0-beta.2](https://github.com/amirnajaffi/shamsi-calendar-plasmoid/releases/tag/2.0.0-beta.2) released.

**Comment by shosseinib** [comment]
Regrettably, I've stopped using KDE Plasma. However, I value the work you've done on this Plasmoid. I intend to review the foundational code once more and should I spot any issues, I'll attempt to rectify them. All the best.

**Comment by shosseinib** [comment]
سعی می‌کنیم پایان هفتهٔ بعد روش کار کنم. فعلا نیاز دارم که قبل از هر چیزی از i3wm به plasma مهاجرت کنم.
