### ISSUE TITLE
Error in the widget

### ISSUE THREAD

**Issue by amirmeimari** [amirnajaffi/shamsi-calendar-plasmoid#12]
file:///home/amir/.local/share/plasma/plasmoids/org.kde.plasma.shamsi-calendar/contents/ui/main.qml:33:32: Type Calendar unavailable

file:///home/amir/.local/share/plasma/plasmoids/org.kde.plasma.shamsi-calendar/contents/ui/Calendar.qml:276:5: Type MonthView unavailable

file:///home/amir/.local/share/plasma/plasmoids/org.kde.plasma.shamsi-calendar/contents/ui/MonthView.qml:75:11: Type RoundedHighlight unavailable

file:///home/amir/.local/share/plasma/plasmoids/org.kde.plasma.shamsi-calendar/contents/ui/RoundedHighlight.qml:5:1: PlasmaExtras.Highlight is not a type

**Comment by amirnajaffi** [comment]
How did you install the widget?
What's output of `plasmashell --version`?

**Comment by amirmeimari** [comment]
I've download the file using this link: https://store.kde.org/p/1460130/, and installed it using `Add widgets +` by clicking on task manager.
  
`plasmashell 5.24.7`

**Comment by amirnajaffi** [comment]
You're installing v1 but errors are for v2 files, it has to be cache problems.

Remove widget first, then run:
`rm -rf /home/amir/.local/share/plasma/plasmoids/org.kde.plasma.shamsi-calendar`
And reboot.
Now install again.

**Comment by amirmeimari** [comment]
Still has that error:
![image](https://github.com/amirnajaffi/shamsi-calendar-plasmoid/assets/34706947/04c8c094-45d0-4584-8686-b5d8fa147a3f)

**Comment by amirmeimari** [comment]
Fixed thanks

**Comment by amirnajaffi** [comment]
As mentioned in [Requirement](https://github.com/amirnajaffi/shamsi-calendar-plasmoid#requirement), you need plasmashell > 5.25
