### ISSUE TITLE
نادرست بودن تاریخ تعطیلات

### ISSUE THREAD

**Issue by MasterKia** [amirnajaffi/shamsi-calendar-plasmoid#19]
طبق سایت `time.ir`، دوم مهر (یک‌شنبه) و یازدهم مهر (سه‌شنبه) تعطیل هست.

https://github.com/amirnajaffi/shamsi-calendar-plasmoid/assets/17685483/1e6fe1be-8c3a-418c-919e-c81c6fcd758b

https://github.com/amirnajaffi/shamsi-calendar-plasmoid/assets/17685483/5be92c35-55f0-4fce-95dc-5bcc492076d7

تاریخ سیستم رو بررسی کردم و درست بود.

**Comment by amirnajaffi** [comment]
Fixed
