### ISSUE TITLE
The date doesn't update automatically

### ISSUE THREAD

**Issue by mahdiar** [amirnajaffi/shamsi-calendar-plasmoid#2]
Hi
I'm using it and it's very useful. Thanks for that.
I have a issue that when my PC is working for a night the date doesn't change to the new one automatically. I should click on Today button to correct the date.

**Comment by amirnajaffi** [comment]
Hi,
I already noticed the problem.
I'm looking for free time to implement this(I have limited time).

**Comment by amirnajaffi** [comment]
Fixed in 26bf40c726cfe7f407c698188967964b9885401f

**Comment by amirnajaffi** [comment]
@mahdiar  I appreciate if you test the new version on your distro and let me know if works properly.

**Comment by mahdiar** [comment]
> @mahdiar I appreciate if you test the new version on your distro and let me know if works properly.

Yes. Thanks!
