### ISSUE TITLE
Adding more events

### ISSUE THREAD

**Issue by mahdiar** [amirnajaffi/shamsi-calendar-plasmoid#4]
Hi
I think it's nice to add more events. You can find theme here:
[https://github.com/SCR-IR/gnome-shamsi-calendar/tree/main/shamsi-calendar%40gnome.scr.ir/events](https://github.com/SCR-IR/gnome-shamsi-calendar/tree/main/shamsi-calendar%40gnome.scr.ir/events)
Regards

**Comment by amirnajaffi** [comment]
Hi
I hope I can do this at the right time. I am not working on this project at the moment.
Thanks for your feedback and supports ❤️

**Comment by amirnajaffi** [comment]
Added 8bb7413
