### ISSUE TITLE
Font rendering issue

### ISSUE THREAD

**Issue by MasterKia** [amirnajaffi/shamsi-calendar-plasmoid#9]
Reproduce in Fedora 36 KDE.
First of all, thank you for creating this awesome widget.

I have this font rendering issue:

![Screenshot_20220729_225920](https://user-images.githubusercontent.com/17685483/181822354-4530bc22-40cf-4913-aa62-a8a419e90b4e.png)
![Screenshot_20220729_225956](https://user-images.githubusercontent.com/17685483/181822417-f5157661-9965-4583-87f6-c496d5cc2f27.png)

Which font should I install to fix this problem?

**Comment by amirnajaffi** [comment]
Hi
There is no custom font included in the project, fonts will inherit from your OS.
You may try changing your OS Persian font. personally, I prefer [Vazir](https://rastikerdar.github.io/vazirmatn/) font.

**Comment by MasterKia** [comment]
Thanks for the tip.

For anyone with the same problem:
1- Install the "Vazirmatn-Regular.ttf" font from [here](https://github.com/rastikerdar/vazirmatn/releases).
2- https://stackoverflow.com/questions/72743838/how-to-change-default-persian-fonts-in-arch:
Create `fonts.conf` file in `~/.config/fontconfig/` and put this inside it:
```xml
<?xml version='1.0'?>
<!DOCTYPE fontconfig SYSTEM 'fonts.dtd'>
<fontconfig>

 <match>
  <edit mode="prepend" name="family">
   <string>Vazirmatn</string>
  </edit>
 </match>

 <dir>~/.local/share/fonts</dir>
 <dir>/usr/share/fonts/</dir>

</fontconfig>
```

3- Restart.

**Comment by MasterKia** [comment]
![Screenshot_20220730_000825](https://user-images.githubusercontent.com/17685483/181832111-f7987dd1-8185-454f-b14e-6f630f728448.png)

Is there anything I can do about the text size? Like making it bigger?

**Comment by amirnajaffi** [comment]
Thanks for sharing your solution.
There are no settings inside the widget to change text size.

**Comment by amirnajaffi** [comment]
> Thanks for sharing your solution. There are no settings inside the widget to change text size.

There is now! dc8fb5e

**Comment by amirnajaffi** [comment]
Yes.
And for now, text on the panel just stays fit to the size of panels like Digital Clock or Event Calendar. It is not configurable yet. check v2 and see if it fits your need and if you still needed to change the panel text size open a new issue and tell why is needed, please.
